In [1]:
import numpy as np


# Numpy exercises

# Array creation

In [2]:
# Create a numpy array of size 10, filled with zeros.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create a numpy array with values ranging from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# Create a numpy matrix of 2*2 integers, filled with ones.
arr = np.ones((2, 2), dtype=int)
arr

array([[1, 1],
       [1, 1]])

In [6]:
#Create a numpy matrix of 3*2 float numbers, filled with ones.
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(4, dtype=int)

np.ones_like(X)


array([1, 1, 1, 1])

In [8]:
# Create a numpy matrix of 4*4 integers, filled with fives.
np.ones([4,4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [11]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[2,3], [6,2]], dtype=int)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [12]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
np.random.randint(10, size=3)

array([1, 7, 0])

In [14]:
#Create a 3*3*3 numpy matrix, filled with random float values.
np.random.randn(3,3,3)

array([[[ 1.53017372,  0.70484678, -0.70444635],
        [ 0.18344544, -0.20603978, -0.51903388],
        [-0.12508366, -0.10950919, -1.30734968]],

       [[ 0.65339685, -0.15290128,  0.73101553],
        [ 1.49186594, -2.01168557, -0.18362894],
        [ 2.08161295,  2.36781657,  0.1344576 ]],

       [[-1.61086595,  1.8767872 , -0.78137908],
        [-0.69983521,  0.0183895 , -0.52942706],
        [ 0.99753466,  0.98150409,  1.06472883]]])

In [16]:
#this also works
np.random.randn(3,3,3)

array([[[ 1.31031229,  0.03851278, -0.69319419],
        [ 0.85939103,  0.76874328, -0.63007814],
        [ 2.14519603, -0.62503496, -0.30860135]],

       [[ 0.17062344, -2.89503467,  0.80705421],
        [ 0.13708796,  1.92427999,  1.06526759],
        [ 2.92861649, -0.37165075, -0.4952991 ]],

       [[ 0.84324889,  0.52769019,  1.78084782],
        [ 0.5908625 ,  0.07484721,  1.82276359],
        [-0.10372881,  0.45891274,  0.48096973]]])

In [15]:
# Given the X python list convert it to an Y numpy array
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # They have diff type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [17]:
# Given the X numpy array, make a copy and store it on Y.
X = np.array([5,2,3], dtype=int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 1773716437008
[5 2 3] 1773716437776


In [18]:
#Create a numpy array with numbers from 1 to 10
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
#Create a numpy array with the odd numbers between 1 to 10
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [20]:
# Create a numpy array with numbers from 1 to 10, in descending order.
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [21]:
#Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Array indexation

In [22]:
#Reverse the given numpy array (first element becomes last)
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

In [23]:

#Order (sort) the given numpy array
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

In [24]:
#Given the X numpy matrix, change the last row with all 1
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

# Boolean arrays (also called masks)

In [25]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [26]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

In [27]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])